name: faim-hcs
dependencies:
  - python==3.9
  - conda-forge::mobie_utils==0.4.2
  - pip
  - pip:
      - prefect
      - git+https://github.com/fmi-faim/faim-hcs@v0.2.0
      - git+https://github.com/fmi-faim/custom-prefect-result@v0.1.4
